### PR TITLE
Specify KMS key to enable Server-Side Encryption

### LINKED ISSUE #7: Enable encryption in resource aws_sns_topic
## Describe the Feature

Enable togglable encryption in resource `aws_sns_topic`.

## Expected Behavior

Encryption should be enabled upon creation of the SNS topic.  A variable should allow for disabling encryption.

## Use Case

Because, ENCRYPTION.

### PR DESCRIPTION
**Pull request by chrispblink**
## what
* A variable has been added to allow users to specify a KMS key ARN for Server-Side Encryption
* This variable defaults to `null` making it optional

## why
* A common use case for SNS messages is processing sensitive data (ex: PII, PHI, payment card)
* Many vendors and government regulators will require end-to-end encryption of this sensitive data

## references
* Resolves #7

### CODE REVIEW

**Review by Ikana — APPROVED** [review]

**Comment by aknysh** [comment]
@chrispblink please rebase

**Review by aknysh — APPROVED** [review]
thanks @chrispblink

**Pull request merged**
