### PR TITLE
feature/kms-optional: Making Encryption configuration of SNS less constraining (also to opt out) 

### PR DESCRIPTION
**Pull request by azec-pdx**
## what
* I was using `cloudposse/terraform-aws-sns-topic` to deploy SNS Topic and subscriber SQS queues for routing Bounce and Complaint notifications from AWS SES service. AWS SES won't accept SNS Topic as the notifications target unless it has enough permissions for KMS key that is configured for SNS Topic Encryption settings. With module `cloudposse/terraform-aws-sns-topic` using default AWS KMS key `alias/aws/sns`, this is limiting in two ways:
  1. It forces users of `cloudposse/terraform-aws-sns-topic` TF module to use encryption even if they don't provide their own KMS key. Users don't have option to deploy SNS Topic with Encryption disabled.
  2. Since users are already forced to use SNS Topic Encryption, their only option becomes to configure their own KMS key and pass it to `cloudposse/terraform-aws-sns-topic` module, but then there is additional requirement for users to do more IAM permissions on KMS key to allow AWS SES service access to the key to encrypt messages as they are fanned out to SNS Topic.
* This PR makes an Encryption settings of SNS Topic deployed with `cloudposse/terraform-aws-sns-topic` optional by providing users with some better choices:
   1. To use their own KMS key if they really want fully customized Encryption configuration of SNS Topic
   2. To opt-in to use default AWS SNS KMS key `alias/aws/sns`
   3. To have Encryption disabled on SNS Topic by default if they don't put effort into 1. and 2.

## why
* Business case: mostly described above, to be able to have better defaults when needing SNS Topic with Encryption disabled in order to work with other AWS service (SES in this case)  - especially since it is all in the same AWS account.
* The PR uses cascading logic for configuring Encryption settings of SNS Topic resource. By introducing `use_default_aws_sns_kms_master_key_id`, and defaulting `kms_master_key_id` to **""**, following cascading logic is applied: 
   * If `use_default_aws_sns_kms_master_key_id` is set explicitly to **true**, no other variables are analyzed. In this case Encryption becomes enabled on SNS Topic and default KMS key `alias/aws/sns` is used in the Encryption configuration.
   * If `use_default_aws_sns_kms_master_key_id` is not set, then variable `kms_master_key_id` is analyzed (see below subcases).
       * If `kms_master_key_id` is set to explicit non-empty value, the Encryption becomes enabled on SNS Topic and user-specified KMS key is used in the Encryption configuration.
       * If `kms_master_key_id` is not passed, then module default value `""` is passed to `aws_sns_topic` resource which then behaves in a way that Encryption on SNS Topic becomes disabled (this was tested and verified).
* This now makes possible to deploy SNS Topic without Encryption by being totally lazy with something like:

   ```terraform
    module "sns" {
       #source = "git::https://github.com/cloudposse/terraform-aws-sns-topic.git//?ref=tags/0.16.0"
       source = "git::https://github.com/SkywardIO/terraform-aws-sns-topic.git//?ref=feature/kms-optional"
       name   = module.this.id

       subscribers                            = var.subscribers
       allowed_aws_services_for_sns_published = var.allowed_aws_services_for_sns_published
       sqs_dlq_enabled                        = false # Until valid case neeed for this and until CP fixes https://github.com/cloudposse/terraform-aws-sns-topic/blob/master/main.tf#L20
   }
   ```
## references
* N/A?

### CODE REVIEW

**Comment by azec-pdx** [comment]
@maximmi, @dakue, @mcalhoun, @chrispblink, @aknysh et. al. 
I will need some help and guidance from you here, as this is first time I am contributing to Cloudposse repo. 
Not really clear why AutoFormat failed since our fork is public repo.

**Comment by joe-niland** [comment]
@azec-pdx can you allow edits from maintainers on your PR?

**Comment by jwstric2** [comment]
@azec-pdx  be happy to help fix issues you have here with auto format, ect.. We hit a similar issue here with encryption being enabled and now we will need to bring along a CMK or disable for cloudwatch alert integration.

**Comment by jwstric2** [comment]
@azec-pdx  I had a SMH moment here after reading the terraform docs.  I think the documentation just needs a minor update to indicate that if the key is set to "" that it will not enable encyrption:

My code base:
```
git diff
diff --git a/providers/aws/us-east-1/main.tf b/providers/aws/us-east-1/main.tf
index 5f293be..447091c 100644
--- a/providers/aws/us-east-1/main.tf
+++ b/providers/aws/us-east-1/main.tf
@@ -1046,6 +1046,7 @@ module "sns_gitlab_slo" {
       raw_message_delivery   = false
     }
   }
+  kms_master_key_id = ""
 }
 

```

terraform plan

```
Terraform will perform the following actions:

  # module.sns_gitlab_slo.data.aws_iam_policy_document.aws_sns_topic_policy will be read during apply
  # (config refers to values not yet known)
 <= data "aws_iam_policy_document" "aws_sns_topic_policy"  {
      ~ id        = (known after apply)
      ~ json      = jsonencode(
            {
              - Id        = "SNSTopicsPub"
              - Statement = [
                  - {
                      - Action    = "sns:Publish"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "cloudwatch.amazonaws.com"
                        }
                      - Resource  = "arn:aws:sns:us-east-1:....:slo"
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
      - version   = "2012-10-17" -> null
        # (1 unchanged attribute hidden)

      ~ statement {
          - not_actions   = [] -> null
          - not_resources = [] -> null
            # (3 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }

  # module.sns_gitlab_slo.aws_sns_topic.this will be updated in-place
  ~ resource "aws_sns_topic" "this" {
        id                                       = "arn:aws:sns:us-east-1:...:slo"
      - kms_master_key_id                        = "alias/aws/sns" -> null
        name                                     = "slo"
        tags                                     = {
            "Name"  = "slo"
            "Stage" = "prod"
        }
        # (7 unchanged attributes hidden)
    }

  # module.sns_gitlab_slo.aws_sns_topic_policy.this will be updated in-place
  ~ resource "aws_sns_topic_policy" "this" {
        id     = "arn:aws:sns:us-east-1:....:slo"
      ~ policy = jsonencode(
            {
              - Id        = "SNSTopicsPub"
              - Statement = [
                  - {
                      - Action    = "sns:Publish"
                      - Effect    = "Allow"
                      - Principal = {
                          - Service = "cloudwatch.amazonaws.com"
                        }
                      - Resource  = "arn:aws:sns:us-east-1:...:slo"
                      - Sid       = ""
                    },
                ]
              - Version   = "2012-10-17"
            }
        ) -> (known after apply)
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy.


```

After apply when viewing through UI:

```
Encryption
Encryption
Disabled
Account
-
Customer master key (CMK)
-
CMK ARN
-
Description
-
```

**Comment by razorsedge** [comment]
Another reason for disabling SNS encryption: [Amazon RDS event notification is only available for unencrypted SNS topics. If you specify an encrypted SNS topic, event notifications aren't sent for the topic.](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_Events.Subscribing.html)

**Comment by azec-pdx** [comment]
Hey there all ! It's been a while I touched this. Let me see if I can refresh and re-kick this PR. It may have ended up with some commits that are unrelated.

**Comment by azec-pdx** [comment]
> @azec-pdx I had a SMH moment here after reading the terraform docs. I think the documentation for this module just needs a minor update to indicate that if the key is set to "" that it will not enable encyrption:
> 
> My code base:
> 
> ```
> git diff
> diff --git a/providers/aws/us-east-1/main.tf b/providers/aws/us-east-1/main.tf
> index 5f293be..447091c 100644
> --- a/providers/aws/us-east-1/main.tf
> +++ b/providers/aws/us-east-1/main.tf
> @@ -1046,6 +1046,7 @@ module "sns_gitlab_slo" {
>        raw_message_delivery   = false
>      }
>    }
> +  kms_master_key_id = ""
>  }
>  
> ```
> 
> terraform plan
> 
> ```
> Terraform will perform the following actions:
> 
>   # module.sns_gitlab_slo.data.aws_iam_policy_document.aws_sns_topic_policy will be read during apply
>   # (config refers to values not yet known)
>  <= data "aws_iam_policy_document" "aws_sns_topic_policy"  {
>       ~ id        = (known after apply)
>       ~ json      = jsonencode(
>             {
>               - Id        = "SNSTopicsPub"
>               - Statement = [
>                   - {
>                       - Action    = "sns:Publish"
>                       - Effect    = "Allow"
>                       - Principal = {
>                           - Service = "cloudwatch.amazonaws.com"
>                         }
>                       - Resource  = "arn:aws:sns:us-east-1:....:slo"
>                       - Sid       = ""
>                     },
>                 ]
>               - Version   = "2012-10-17"
>             }
>         ) -> (known after apply)
>       - version   = "2012-10-17" -> null
>         # (1 unchanged attribute hidden)
> 
>       ~ statement {
>           - not_actions   = [] -> null
>           - not_resources = [] -> null
>             # (3 unchanged attributes hidden)
> 
>             # (1 unchanged block hidden)
>         }
>     }
> 
>   # module.sns_gitlab_slo.aws_sns_topic.this will be updated in-place
>   ~ resource "aws_sns_topic" "this" {
>         id                                       = "arn:aws:sns:us-east-1:...:slo"
>       - kms_master_key_id                        = "alias/aws/sns" -> null
>         name                                     = "slo"
>         tags                                     = {
>             "Name"  = "slo"
>             "Stage" = "prod"
>         }
>         # (7 unchanged attributes hidden)
>     }
> 
>   # module.sns_gitlab_slo.aws_sns_topic_policy.this will be updated in-place
>   ~ resource "aws_sns_topic_policy" "this" {
>         id     = "arn:aws:sns:us-east-1:....:slo"
>       ~ policy = jsonencode(
>             {
>               - Id        = "SNSTopicsPub"
>               - Statement = [
>                   - {
>                       - Action    = "sns:Publish"
>                       - Effect    = "Allow"
>                       - Principal = {
>                           - Service = "cloudwatch.amazonaws.com"
>                         }
>                       - Resource  = "arn:aws:sns:us-east-1:...:slo"
>                       - Sid       = ""
>                     },
>                 ]
>               - Version   = "2012-10-17"
>             }
>         ) -> (known after apply)
>         # (1 unchanged attribute hidden)
>     }
> 
> Plan: 0 to add, 2 to change, 0 to destroy.
> ```
> 
> After apply when viewing through UI:
> 
> ```
> Encryption
> Encryption
> Disabled
> Account
> -
> Customer master key (CMK)
> -
> CMK ARN
> -
> Description
> -
> ```

**Comment by azec-pdx** [comment]
Reopened as https://github.com/cloudposse/terraform-aws-sns-topic/pull/34 after some rebasing issues of our fork ...

**Pull request closed without merging**
