### PR TITLE
Allow publish permissions for IAM role/user ARNs

### PR DESCRIPTION
**Pull request by chrispblink**
## what
* The SNS topic policy will have a new `principals` block with specified IAM role/user ARNs
* The block was made `dynamic` to allow this feature to be optional (when IAM ARNs are not specified)

## why
* A very common use case for SNS is a customer-hosted app publishing to the topic
* Customer-hosted apps will authenticate as an IAM ARN, thus we add a `principals` block with the type `AWS`

## references
* N/A

### CODE REVIEW

**Review by Ikana — APPROVED** [review]

**Review by aknysh — APPROVED** [review]
thanks @chrispblink

**Pull request merged**
