### PR TITLE
remove notice about redrive_policy from readme

### PR DESCRIPTION
**Pull request by shinenelson**
## what
redrive_plicy was added in e932f7e ( tag:v0.20.0 ), but this notice was missed to be removed.

## why
the notice could be misleading to users who visit the module's readme and see the notice even though the feature already exists in the module.

## references
- https://github.com/terraform-providers/terraform-provider-aws/pull/11770
- e932f7e ( tag:v0.20.0 )

### CODE REVIEW

**Comment by khdevel** [comment]
@shinenelson I think that you should also include usage of the `redrive_policy` and `redrive_allow_policy` variables in the [sqs_queue](https://github.com/cloudposse/terraform-aws-sns-topic/blob/0.20.1/main.tf#L78) resource.

**Comment by acorncom** [comment]
Is it possible to get this change in? Hard to tell the state of this module when reading over the Readme ... :-)

**Comment by Gowiem** [comment]
@shinenelson thanks for this small docs update, it's much appreciated! We'll work to get this merged. 

Could I also bug you to open an issue so we have a means by tracking the addition of `redrive_policy`? That way maybe a contributor who needs it will see that and add it in a future PR?

**Comment by Gowiem** [comment]
Ah we release a v0.20 of this module and it added support for `redrive_policy`. Nevermind on creating that issue @shinenelson!

We have issues with the README here. I am going to fix via a separate PR and we'll get this change in. Will close this via another PR.

**Comment by Gowiem** [comment]
Thanks for the help in pushing this forward @shinenelson @khdevel and @acorncom!

**Pull request closed without merging**
