### PR TITLE
Add raw_message_delivery to subscribers

### PR DESCRIPTION
**Pull request by dakue**
## what
Add the posibility to configure the raw_message_delivery attribute of the aws_sns_topic_subscription

## why
The fields in the SNS json schema where just overhead for us and to keep it lean we just wanted to transfer our own json.

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]

**Comment by dakue** [comment]
Hello @Gowiem , @osterman ,

the readme test seems to be failing on a sorting issue. Are you using a special terraform-docs configuration / version?

**Comment by SweetOps** [comment]
@dakue could you run the following commands locally and commit:

```
make init
make readme
terraform fmt
```

**Comment by osterman** [comment]
(note there have been 2 new releases of `terraform-docs`, and we validate against the latest release)

**Comment by dakue** [comment]
Hello @osterman,

thanks for the hint. I hopefully fixed the README now. I used terraform-docs 0.11.2.

**Review by SweetOps — APPROVED** [review]

**Pull request merged**
